### 用户列表
GET http://{{host}}/users
Accept: application/json

### 用户详情
GET http://{{host}}/users/650a914d540334004243cad9


### 创建用户
POST http://{{host}}/users
Content-Type: application/json

{
  "name": "许梦龙1"
}


### 更新用户
PUT http://{{host}}/users/650a914d540334004243cad9
Content-Type: application/json

{
  "name": "许一诺"
}


### 删除用户
DELETE http://{{host}}/users/650a914d540334004243cad9

