### 用户列表
GET http://{{host}}/users?per_page=10&page=2
Accept: application/json

### 用户详情
GET http://{{host}}/users/650a93326d5a6b7b68a4b31b?fields=employments;educations;locations;following;
Authorization: Bearer {{token}}


### 创建用户
POST http://{{host}}/users
Content-Type: application/json

{
  "name": "admin10",
  "password": "123456"
}


### 更新用户
PATCH http://{{host}}/users/650a93326d5a6b7b68a4b31b
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "admin",
  "avatar_url": "http://localhost:3000/uploads/upload_c45810cec65a4ee0fd8456112757baf4.png",
  "headline": "我是一只小小小小鸟"
}


### 删除用户
DELETE http://{{host}}/users/650a914d540334004243cad9
Authorization: Bearer {{token}}


### 用户登录
POST http://{{host}}/users/login
Content-Type: application/json

{
  "name": "admin",
  "password": "123456"
}

> {%
  client.global.set('token', response.body.token)
%}


### 文件上传
# https://www.bilibili.com/video/BV1NF411y7SF
POST http://{{host}}/upload
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="upload.txt"

< ./upload.txt

--boundary--


### 用户粉丝列表
GET http://{{host}}/users/650a9136540334004243cad7/followers

### 关注用户列表
GET http://{{host}}/users/650a93326d5a6b7b68a4b31b/following


### 关注用户
PUT http://{{host}}/users/following/650a93326d5a6b7b68a4b31b
Authorization: Bearer {{token}}

### 取消关注用户
DELETE http://{{host}}/users/following/650a9136540334004243cad7
Authorization: Bearer {{token}}


### 话题列表
GET http://{{host}}/topics

### 话题详情
GET http://{{host}}/topics/650aaa21085a038417e7055e?fields=introduction;

### 创建话题
POST http://{{host}}/topics
Authorization: Bearer {{token}}
Content-Type: application/json

{
"name":"这个一个话题",
"introduction":"这个一个话题的介绍"
}


### 更新话题
PATCH http://{{host}}/topics/650aaa21085a038417e7055e
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "这个一个话题1"
}
